import Config from '../../../config/config';

const CustomerMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Customer Management',
        aliasname: 'customermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'name',
                text: 'Customer Name',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Customer Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Customer Name',
                label: 'Customer Name',
            },
            {
                field: 'email',
                text: 'Email Address',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'customer@example.com',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Email Address',
                label: 'Email Address',
            },
            {
                field: 'phone',
                text: 'Phone Number',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '+91-9876543210',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Phone Number',
                label: 'Phone Number',
            },
            {
                field: 'status',
                text: 'Customer Status',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Status',
                defaultvalue: 'active',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Status',
                label: 'Customer Status',
                options: [
                    { value: 'active', label: 'Active' },
                    { value: 'inactive', label: 'Inactive' },
                    { value: 'suspended', label: 'Suspended' },
                    { value: 'blacklisted', label: 'Blacklisted' }
                ]
            },
            {
                field: 'totalOrders',
                text: 'Total Orders',
                type: 'number',
                disabled: true,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '0',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Order Count',
                label: 'Total Orders',
            },
            {
                field: 'totalSpent',
                text: 'Total Spent',
                type: 'number',
                disabled: true,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '0.00',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Amount',
                label: 'Total Spent',
            },
            {
                field: 'lastOrderDate',
                text: 'Last Order Date',
                type: 'datepicker',
                disabled: true,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Last order date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select date range',
                label: 'Last Order Date',
            },
        ],
    },

    // ─── Tab 2: Address Information ─────────────────────────────────────
    {
        tabname: 'Address Information',
        pagename: 'Customer Management',
        aliasname: 'customermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'shippingAddress',
                text: 'Shipping Address',
                type: 'textarea',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter complete shipping address',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Shipping Address',
            },
            {
                field: 'city',
                text: 'City',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter city',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter City',
                label: 'City',
            },
            {
                field: 'state',
                text: 'State',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter state',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter State',
                label: 'State',
            },
            {
                field: 'pincode',
                text: 'Pincode',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter pincode',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Pincode',
                label: 'Pincode',
            },
            {
                field: 'country',
                text: 'Country',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select Country',
                defaultvalue: 'india',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Country',
                label: 'Country',
                options: [
                    { value: 'india', label: 'India' },
                    { value: 'usa', label: 'United States' },
                    { value: 'uk', label: 'United Kingdom' },
                    { value: 'canada', label: 'Canada' },
                    { value: 'australia', label: 'Australia' },
                    { value: 'other', label: 'Other' }
                ]
            },
        ],
    },

    // ─── Tab 3: Preferences & Notes ─────────────────────────────────────
    {
        tabname: 'Preferences & Notes',
        pagename: 'Customer Management',
        aliasname: 'customermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'preferredCommunication',
                text: 'Preferred Communication',
                type: 'dropdown',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select preference',
                defaultvalue: 'email',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Preference',
                label: 'Preferred Communication',
                options: [
                    { value: 'email', label: 'Email' },
                    { value: 'phone', label: 'Phone' },
                    { value: 'sms', label: 'SMS' },
                    { value: 'whatsapp', label: 'WhatsApp' }
                ]
            },
            {
                field: 'marketingConsent',
                text: 'Marketing Consent',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Marketing consent',
                defaultvalue: 0,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-150p',
                filter: 0,
                label: 'Marketing Consent',
            },
            {
                field: 'customerNotes',
                text: 'Customer Notes',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter customer notes',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Customer Notes',
            },
            {
                field: 'tags',
                text: 'Customer Tags',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter tags separated by commas',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Customer Tags',
            },
        ],
    },
];

export default CustomerMasterJson;
