import Config from '../../../config/config';

const InventoryMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Inventory Management',
        aliasname: 'inventorymaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'productName',
                text: 'Product Name',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Product Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Product Name',
                label: 'Product Name',
            },
            {
                field: 'sku',
                text: 'SKU',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter SKU',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter SKU',
                label: 'SKU',
            },
            {
                field: 'category',
                text: 'Category',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Category',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Category',
                label: 'Category',
                options: [
                    { value: 'necklaces', label: 'Necklaces' },
                    { value: 'earrings', label: 'Earrings' },
                    { value: 'rings', label: 'Rings' },
                    { value: 'bracelets', label: 'Bracelets' },
                    { value: 'pendants', label: 'Pendants' },
                    { value: 'chains', label: 'Chains' },
                    { value: 'other', label: 'Other' }
                ]
            },
            {
                field: 'currentStock',
                text: 'Current Stock',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter current stock',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Stock Quantity',
                label: 'Current Stock',
            },
            {
                field: 'threshold',
                text: 'Low Stock Threshold',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter threshold',
                defaultvalue: 5,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Threshold',
                label: 'Low Stock Threshold',
            },
            {
                field: 'price',
                text: 'Price',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter price',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Price',
                label: 'Price',
            },
            {
                field: 'status',
                text: 'Stock Status',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'In Stock',
                defaultvalue: 1,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-120p',
                filter: 0,
                label: 'In Stock',
            },
        ],
    },

    // ─── Tab 2: Product Details ─────────────────────────────────────
    {
        tabname: 'Product Details',
        pagename: 'Inventory Management',
        aliasname: 'inventorymaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'description',
                text: 'Description',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter product description',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Description',
            },
            {
                field: 'specifications',
                text: 'Specifications',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter product specifications',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Specifications',
            },
            {
                field: 'weight',
                text: 'Weight (grams)',
                type: 'number',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter weight in grams',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Weight',
                label: 'Weight (grams)',
            },
            {
                field: 'dimensions',
                text: 'Dimensions (L×W×H mm)',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter L×W×H',
                defaultvalue: '',
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-150p',
                filter: 0,
                label: 'Dimensions (L×W×H mm)',
            },
        ],
    },

    // ─── Tab 3: Media & Images ─────────────────────────────────────
    {
        tabname: 'Media & Images',
        pagename: 'Inventory Management',
        aliasname: 'inventorymaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'images',
                text: 'Product Images',
                type: 'multipleimage',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Upload product images',
                defaultvalue: [],
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Product Images',
            },
            {
                field: 'thumbnail',
                text: 'Thumbnail Image',
                type: 'image',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Upload thumbnail',
                defaultvalue: '',
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-150p',
                filter: 0,
                label: 'Thumbnail Image',
            },
            {
                field: 'tags',
                text: 'Product Tags',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter tags separated by commas',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Product Tags',
            },
        ],
    },
];

export default InventoryMasterJson;
