import Config from '../../../config/config';

const OrderMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Order Management',
        aliasname: 'ordermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'orderNumber',
                text: 'Order Number',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Auto-generated',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Order Number',
                label: 'Order Number',
            },
            {
                field: 'customerName',
                text: 'Customer Name',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Customer Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Customer Name',
                label: 'Customer Name',
            },
            {
                field: 'customerEmail',
                text: 'Customer Email',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'customer@example.com',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Email',
                label: 'Customer Email',
            },
            {
                field: 'customerPhone',
                text: 'Customer Phone',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: '+91-9876543210',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Phone',
                label: 'Customer Phone',
            },
            {
                field: 'status',
                text: 'Order Status',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Status',
                defaultvalue: 'pending',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Status',
                label: 'Order Status',
                options: [
                    { value: 'pending', label: 'Pending' },
                    { value: 'confirmed', label: 'Confirmed' },
                    { value: 'processing', label: 'Processing' },
                    { value: 'shipped', label: 'Shipped' },
                    { value: 'delivered', label: 'Delivered' },
                    { value: 'cancelled', label: 'Cancelled' },
                    { value: 'returned', label: 'Returned' },
                    { value: 'refunded', label: 'Refunded' }
                ]
            },
            {
                field: 'paymentStatus',
                text: 'Payment Status',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Payment Status',
                defaultvalue: 'pending',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Payment Status',
                label: 'Payment Status',
                options: [
                    { value: 'pending', label: 'Pending' },
                    { value: 'paid', label: 'Paid' },
                    { value: 'failed', label: 'Failed' },
                    { value: 'refunded', label: 'Refunded' }
                ]
            },
            {
                field: 'totalAmount',
                text: 'Total Amount',
                type: 'number',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '0.00',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Amount',
                label: 'Total Amount',
            },
        ],
    },

    // ─── Tab 2: Shipping Information ─────────────────────────────────────
    {
        tabname: 'Shipping Information',
        pagename: 'Order Management',
        aliasname: 'ordermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'shippingAddress',
                text: 'Shipping Address',
                type: 'textarea',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter complete shipping address',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Shipping Address',
            },
            {
                field: 'city',
                text: 'City',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter city',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter City',
                label: 'City',
            },
            {
                field: 'state',
                text: 'State',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter state',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter State',
                label: 'State',
            },
            {
                field: 'pincode',
                text: 'Pincode',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter pincode',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Pincode',
                label: 'Pincode',
            },
            {
                field: 'deliveryInstructions',
                text: 'Delivery Instructions',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter special delivery instructions',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Delivery Instructions',
            },
        ],
    },

    // ─── Tab 3: Order Items ─────────────────────────────────────
    {
        tabname: 'Order Items',
        pagename: 'Order Management',
        aliasname: 'ordermaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'items',
                text: 'Order Items',
                type: 'multipleimage',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Add order items',
                defaultvalue: [],
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Order Items',
            },
            {
                field: 'orderNotes',
                text: 'Order Notes',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter order notes',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Order Notes',
            },
        ],
    },
];

export default OrderMasterJson;
