import Config from '../../../config/config';

const ReturnRefundMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Return & Refund Management',
        aliasname: 'returnrefundmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'orderNumber',
                text: 'Order Number',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Auto-generated',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Order Number',
                label: 'Order Number',
            },
            {
                field: 'customerName',
                text: 'Customer Name',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Customer Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Customer Name',
                label: 'Customer Name',
            },
            {
                field: 'status',
                text: 'Return Status',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Status',
                defaultvalue: 'requested',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Status',
                label: 'Return Status',
                options: [
                    { value: 'requested', label: 'Requested' },
                    { value: 'approved', label: 'Approved' },
                    { value: 'rejected', label: 'Rejected' },
                    { value: 'pickup_scheduled', label: 'Pickup Scheduled' },
                    { value: 'in_transit', label: 'In Transit' },
                    { value: 'received', label: 'Received' },
                    { value: 'refund_pending', label: 'Refund Pending' },
                    { value: 'refunded', label: 'Refunded' },
                    { value: 'closed', label: 'Closed' }
                ]
            },
            {
                field: 'reason',
                text: 'Return Reason',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Select return reason',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Reason',
                label: 'Return Reason',
                options: [
                    { value: 'wrong_item', label: 'Wrong Item Delivered' },
                    { value: 'damaged_item', label: 'Item Damaged' },
                    { value: 'not_as_described', label: 'Not as Described' },
                    { value: 'size_issue', label: 'Size Issue' },
                    { value: 'quality_issue', label: 'Quality Issue' },
                    { value: 'changed_mind', label: 'Changed Mind' },
                    { value: 'defective', label: 'Defective Product' },
                    { value: 'other', label: 'Other' }
                ]
            },
            {
                field: 'totalAmount',
                text: 'Return Amount',
                type: 'number',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '0.00',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Amount',
                label: 'Return Amount',
            },
            {
                field: 'requestedAt',
                text: 'Requested At',
                type: 'datepicker',
                disabled: true,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Request date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select date range',
                label: 'Requested At',
            },
        ],
    },

    // ─── Tab 2: Return Details ─────────────────────────────────────
    {
        tabname: 'Return Details',
        pagename: 'Return & Refund Management',
        aliasname: 'returnrefundmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'customerNote',
                text: 'Customer Note',
                type: 'textarea',
                disabled: true,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Customer notes about return',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Customer Note',
            },
            {
                field: 'requestProofUrls',
                text: 'Request Proof Images',
                type: 'multipleimage',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Upload proof images',
                defaultvalue: [],
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Request Proof Images',
            },
            {
                field: 'approvalNote',
                text: 'Approval Note',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter approval/rejection notes',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Approval Note',
            },
            {
                field: 'approvedAt',
                text: 'Approved At',
                type: 'datepicker',
                disabled: true,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Approval date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select date range',
                label: 'Approved At',
            },
            {
                field: 'pickupScheduledAt',
                text: 'Pickup Scheduled At',
                type: 'datepicker',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Schedule pickup date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select date range',
                label: 'Pickup Scheduled At',
            },
        ],
    },

    // ─── Tab 3: Refund Information ─────────────────────────────────────
    {
        tabname: 'Refund Information',
        pagename: 'Return & Refund Management',
        aliasname: 'returnrefundmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'refundStatus',
                text: 'Refund Status',
                type: 'dropdown',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select refund status',
                defaultvalue: 'not_started',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Refund Status',
                label: 'Refund Status',
                options: [
                    { value: 'not_started', label: 'Not Started' },
                    { value: 'pending', label: 'Pending' },
                    { value: 'processed', label: 'Processed' },
                    { value: 'failed', label: 'Failed' }
                ]
            },
            {
                field: 'refundMethod',
                text: 'Refund Method',
                type: 'dropdown',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select refund method',
                defaultvalue: 'original_payment',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Method',
                label: 'Refund Method',
                options: [
                    { value: 'original_payment', label: 'Original Payment' },
                    { value: 'bank_transfer', label: 'Bank Transfer' },
                    { value: 'upi', label: 'UPI' },
                    { value: 'wallet', label: 'Wallet Credit' },
                    { value: 'store_credit', label: 'Store Credit' }
                ]
            },
            {
                field: 'refundReference',
                text: 'Refund Reference',
                type: 'text',
                disabled: true,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Auto-generated',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Reference',
                label: 'Refund Reference',
            },
            {
                field: 'refundProofUrls',
                text: 'Refund Proof Images',
                type: 'multipleimage',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Upload refund proof images',
                defaultvalue: [],
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Refund Proof Images',
            },
            {
                field: 'refundNote',
                text: 'Refund Note',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter refund processing notes',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Refund Note',
            },
        ],
    },
];

export default ReturnRefundMasterJson;
