import Config from '../../../config/config';

const ShippingMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Shipping Management',
        aliasname: 'shippingmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'orderNumber',
                text: 'Order Number',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Auto-generated',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Order Number',
                label: 'Order Number',
            },
            {
                field: 'customerName',
                text: 'Customer Name',
                type: 'text',
                disabled: true,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Customer Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Customer Name',
                label: 'Customer Name',
            },
            {
                field: 'courierName',
                text: 'Courier Name',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Courier',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Courier',
                label: 'Courier Name',
                options: [
                    { value: 'delhivery', label: 'Delhivery' },
                    { value: 'bluedart', label: 'Blue Dart' },
                    { value: 'fedex', label: 'FedEx' },
                    { value: 'dhl', label: 'DHL' },
                    { value: 'xpressbees', label: 'Xpressbees' }
                ]
            },
            {
                field: 'awbNumber',
                text: 'AWB Number',
                type: 'text',
                disabled: true,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Auto-generated',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter AWB Number',
                label: 'AWB Number',
            },
            {
                field: 'status',
                text: 'Shipping Status',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Status',
                defaultvalue: 'assigned',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Status',
                label: 'Shipping Status',
                options: [
                    { value: 'assigned', label: 'Assigned' },
                    { value: 'pickup_scheduled', label: 'Pickup Scheduled' },
                    { value: 'picked_up', label: 'Picked Up' },
                    { value: 'in_transit', label: 'In Transit' },
                    { value: 'out_for_delivery', label: 'Out for Delivery' },
                    { value: 'delivered', label: 'Delivered' },
                    { value: 'exception', label: 'Exception' }
                ]
            },
            {
                field: 'weight',
                text: 'Weight (kg)',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter weight in kg',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'number',
                filterplaceholder: 'Enter Weight',
                label: 'Weight (kg)',
            },
            {
                field: 'dimensions',
                text: 'Dimensions (L×W×H cm)',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Enter L×W×H',
                defaultvalue: '',
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-150p',
                filter: 0,
                label: 'Dimensions (L×W×H cm)',
            },
        ],
    },

    // ─── Tab 2: Tracking & Timeline ─────────────────────────────────────
    {
        tabname: 'Tracking & Timeline',
        pagename: 'Shipping Management',
        aliasname: 'shippingmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'trackingUrl',
                text: 'Tracking URL',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter tracking URL',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-200p',
                filter: 0,
                label: 'Tracking URL',
            },
            {
                field: 'estimatedDelivery',
                text: 'Estimated Delivery',
                type: 'datepicker',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select delivery date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select delivery date range',
                label: 'Estimated Delivery',
            },
            {
                field: 'pickupDate',
                text: 'Pickup Date',
                type: 'datepicker',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select pickup date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select pickup date range',
                label: 'Pickup Date',
            },
            {
                field: 'notes',
                text: 'Shipping Notes',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter any special instructions',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Shipping Notes',
            },
        ],
    },

    // ─── Tab 3: Exception Handling ─────────────────────────────────────
    {
        tabname: 'Exception Handling',
        pagename: 'Shipping Management',
        aliasname: 'shippingmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'exceptionStatus',
                text: 'Exception Status',
                type: 'dropdown',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select exception status',
                defaultvalue: 'none',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'dropdown',
                filterplaceholder: 'Select Exception Status',
                label: 'Exception Status',
                options: [
                    { value: 'none', label: 'No Exception' },
                    { value: 'address_not_found', label: 'Address Not Found' },
                    { value: 'recipient_unavailable', label: 'Recipient Unavailable' },
                    { value: 'package_damaged', label: 'Package Damaged' },
                    { value: 'weather_delay', label: 'Weather Delay' },
                    { value: 'customs_hold', label: 'Customs Hold' },
                    { value: 'other', label: 'Other' }
                ]
            },
            {
                field: 'exceptionMessage',
                text: 'Exception Message',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Describe the exception',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Exception Message',
            },
            {
                field: 'exceptionResolvedAt',
                text: 'Exception Resolved At',
                type: 'datepicker',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12 col-md-6',
                placeholder: 'Select resolution date',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'daterange',
                filterplaceholder: 'Select resolution date range',
                label: 'Exception Resolved At',
            },
            {
                field: 'resolutionNotes',
                text: 'Resolution Notes',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: false,
                size: 'col-12',
                placeholder: 'Enter resolution details',
                defaultvalue: '',
                showingrid: false,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
                label: 'Resolution Notes',
            },
        ],
    },
];

export default ShippingMasterJson;
