const CmsContactMasterJson = [
    {
        tabname: 'Contact page',
        pagename: 'Contact Page (storefront)',
        aliasname: 'cmscontact',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'pageTitle',
                text: 'Page title',
                type: 'text',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: 'Contact ORINKET',
            },
            {
                field: 'subtitle',
                text: 'Subtitle',
                type: 'textarea',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'email',
                text: 'Email',
                type: 'text',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'phone',
                text: 'Phone',
                type: 'text',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'address',
                text: 'Address',
                type: 'textarea',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'hours',
                text: 'Support hours',
                type: 'text',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'hoursNote',
                text: 'Note under hours',
                type: 'textarea',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
            },
            {
                field: 'brandDisplayName',
                text: 'Brand name in heading (optional)',
                type: 'text',
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                placeholder: 'Leave blank to use store name from General Settings',
            },
        ],
    },
];

export default CmsContactMasterJson;
