const CmsFaqMasterJson = [
    {
        tabname: 'FAQ',
        pagename: 'FAQ Master',
        aliasname: 'cmsfaq',
        rightsidebarsize: 'md',
        fields: [
            {
                field: 'groupTitle',
                text: 'Group / section title',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                label: 'Group',
            },
            {
                field: 'question',
                text: 'Question',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-280p',
                filter: 1,
                filtertype: 'text',
                label: 'Question',
            },
            {
                field: 'answer',
                text: 'Answer',
                type: 'textarea',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-320p',
                filter: 0,
                label: 'Answer',
            },
            {
                field: 'sortOrder',
                text: 'Sort order',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: 0,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 0,
                label: 'Order',
            },
            {
                field: 'status',
                text: 'Active',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: 1,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-100p',
                filter: 0,
            },
        ],
    },
];

export default CmsFaqMasterJson;
