/**
 * Route metadata only (no React components) — safe to import from Dashboard without circular deps with RouteConfig.
 */
export const FLAT_ROUTES_META = [
    { path: '/dashboard', pageKey: null, label: 'Home', showInSidebar: true },
    { path: '/allmaster', pageKey: null, label: 'All Masters', showInSidebar: false },
    { path: '/menumaster', pageKey: 'menumaster', label: 'Menu Master', showInSidebar: true },
    { path: '/iconmaster', pageKey: 'iconmaster', label: 'Icon Master', showInSidebar: true },
    { path: '/modulemaster', pageKey: 'modulemaster', label: 'Module Master', showInSidebar: true },
    { path: '/menuassignmaster', pageKey: 'menuassignmaster', label: 'Menu Assign', showInSidebar: true },
    { path: '/seriesassignmaster', pageKey: 'seriesassignmaster', label: 'Series Assign', showInSidebar: true },
    { path: '/category', pageKey: 'category', label: 'Category', showInSidebar: true },
    { path: '/usermaster', pageKey: 'usermaster', label: 'User Master', showInSidebar: true },
    { path: '/userrole', pageKey: 'userrole', label: 'User Role', showInSidebar: true },
    { path: '/seriesmaster', pageKey: 'seriesmaster', label: 'Series Master', showInSidebar: true },
    { path: '/countrymaster', pageKey: 'countrymaster', label: 'Country Master', showInSidebar: true },
    { path: '/citymaster', pageKey: 'citymaster', label: 'City Master', showInSidebar: true },
    { path: '/statemaster', pageKey: 'statemaster', label: 'State Master', showInSidebar: true },
    { path: '/productmaster', pageKey: 'productmaster', label: 'Product Master', showInSidebar: true },
    {
        path: '/low-stock-threshold-master',
        pageKey: 'lowstockthresholdmaster',
        label: 'Low stock threshold',
        showInSidebar: true,
    },
    {
        path: '/low-stock-products-master',
        pageKey: 'lowstockproductsmaster',
        label: 'Low Stock Master',
        showInSidebar: true,
    },
    {
        path: '/storefront-orders',
        pageKey: 'storefrontorders',
        label: 'Storefront orders',
        showInSidebar: true,
    },
    {
        path: '/order-management/*',
        pageKey: 'ordermanagement',
        label: 'Order management',
        showInSidebar: true,
    },
    { path: '/subcategorymaster', pageKey: 'subcategorymaster', label: 'Sub Category Master', showInSidebar: true },
    { path: '/occasionmaster', pageKey: 'occasionmaster', label: 'Occasion Master', showInSidebar: true },
    { path: '/generalsetting', pageKey: 'generalsetting', label: 'General Settings', showInSidebar: true },
    { path: '/storefronthomepage', pageKey: 'storefronthomepage', label: 'Storefront homepage', showInSidebar: true },
    { path: '/storefrontsections', pageKey: 'storefrontsections', label: 'Storefront sections', showInSidebar: true },
    { path: '/demifinemaster', pageKey: 'storefrontdemifinemaster', label: 'Storefront Demifine', showInSidebar: true },
    { path: '/discount-banner-master', pageKey: 'storefrontdiscountbannermaster', label: 'Storefront Discount Banner', showInSidebar: true },
    { path: '/shop-by-recipient-master', pageKey: 'storefrontshopbyrecipientmaster', label: 'Storefront Shop By Recipient', showInSidebar: true },
    { path: '/for-every-you-master', pageKey: 'storefrontforeveryyoumaster', label: 'Storefront For Every You', showInSidebar: true },
    { path: '/fine-gold-master', pageKey: 'storefrontfinegoldmaster', label: 'Storefront Fine Gold', showInSidebar: true },
    { path: '/deserve-to-shine-master', pageKey: 'storefrontdeservetoshinemaster', label: 'Storefront Deserve To Shine', showInSidebar: true },
    { path: '/founder-message-master', pageKey: 'storefrontfoundermessagemaster', label: 'Storefront Founder Message', showInSidebar: true },
    { path: '/blog-section-master', pageKey: 'storefrontblogsectionmaster', label: 'Blog Master', showInSidebar: true },
    { path: '/shop-with-confidence-master', pageKey: 'storefrontshopwithconfidencemaster', label: 'Storefront Shop With Confidence', showInSidebar: true },
    { path: '/brand-story-master', pageKey: 'storefrontbrandstorymaster', label: 'Storefront Brand Story', showInSidebar: true },
    { path: '/reviews-master', pageKey: 'storefrontreviewsmaster', label: 'Storefront Reviews', showInSidebar: true },
    { path: '/spinlogmaster', pageKey: 'spinlogmaster', label: 'Spin logs', showInSidebar: true },
    { path: '/cta-banner-master', pageKey: 'storefrontctabannermaster', label: 'Storefront CTA Banner', showInSidebar: true },
    { path: '/visit-stores-master', pageKey: 'storefrontvisitstoresmaster', label: 'Storefront Visit Stores', showInSidebar: true },
    { path: '/cmscontact', pageKey: 'cmscontact', label: 'Contact page', showInSidebar: true },
    { path: '/cmsfaq', pageKey: 'cmsfaq', label: 'FAQ Master', showInSidebar: true },
    { path: '/cmsshipping', pageKey: 'cmsshipping', label: 'Shipping page', showInSidebar: true },
    { path: '/cmsreturns', pageKey: 'cmsreturns', label: 'Returns & exchanges', showInSidebar: true },
    { path: '/user-logins', pageKey: 'userlogins', label: 'User Login History', showInSidebar: true },
    { path: '/my-profile', pageKey: null, label: 'My Profile', showInSidebar: false },
    { path: '/account-settings', pageKey: null, label: 'Account Settings', showInSidebar: false },
    { path: '/my-devices', pageKey: null, label: 'My Devices', showInSidebar: false },
    { path: '/workspace/activity', pageKey: null, label: 'Activity Log', showInSidebar: false },
    { path: '/workspace/help', pageKey: null, label: 'Need Help', showInSidebar: false },
    { path: '/workspace/feedback', pageKey: null, label: 'Send Feedback', showInSidebar: false },
];
