/**
 * Route metadata only (no React components) — safe to import from Dashboard without circular deps with RouteConfig.
 */
export const FLAT_ROUTES_META = [
    { path: '/dashboard', pageKey: null, label: 'Home', showInSidebar: true },
    { path: '/allmaster', pageKey: null, label: 'All Masters', showInSidebar: false },
    { path: '/menumaster', pageKey: 'menumaster', label: 'Menu Master', showInSidebar: true },
    { path: '/iconmaster', pageKey: 'iconmaster', label: 'Icon Master', showInSidebar: true },
    { path: '/modulemaster', pageKey: 'modulemaster', label: 'Module Master', showInSidebar: true },
    { path: '/menuassignmaster', pageKey: 'menuassignmaster', label: 'Menu Assign', showInSidebar: true },
    { path: '/seriesassignmaster', pageKey: 'seriesassignmaster', label: 'Series Assign', showInSidebar: true },
    { path: '/category', pageKey: 'category', label: 'Category', showInSidebar: true },
    { path: '/usermaster', pageKey: 'usermaster', label: 'User Master', showInSidebar: true },
    { path: '/userrole', pageKey: 'userrole', label: 'User Role', showInSidebar: true },
    { path: '/seriesmaster', pageKey: 'seriesmaster', label: 'Series Master', showInSidebar: true },
    { path: '/countrymaster', pageKey: 'countrymaster', label: 'Country Master', showInSidebar: true },
    { path: '/citymaster', pageKey: 'citymaster', label: 'City Master', showInSidebar: true },
    { path: '/statemaster', pageKey: 'statemaster', label: 'State Master', showInSidebar: true },
    { path: '/productmaster', pageKey: 'productmaster', label: 'Product Master', showInSidebar: true },
    { path: '/subcategorymaster', pageKey: 'subcategorymaster', label: 'Sub Category Master', showInSidebar: true },
    { path: '/generalsetting', pageKey: 'generalsetting', label: 'General Settings', showInSidebar: true },
    { path: '/storefronthomepage', pageKey: 'storefronthomepage', label: 'Storefront homepage', showInSidebar: true },
    { path: '/storefrontsections', pageKey: 'storefrontsections', label: 'Storefront sections', showInSidebar: true },
    { path: '/demifinemaster', pageKey: 'storefrontdemifinemaster', label: 'Storefront Demifine', showInSidebar: true },
    { path: '/top-styles-master', pageKey: 'storefronttopstylesmaster', label: 'Storefront Top Styles', showInSidebar: true },
    { path: '/discount-banner-master', pageKey: 'storefrontdiscountbannermaster', label: 'Storefront Discount Banner', showInSidebar: true },
    { path: '/shop-by-recipient-master', pageKey: 'storefrontshopbyrecipientmaster', label: 'Storefront Shop By Recipient', showInSidebar: true },
    { path: '/for-every-you-master', pageKey: 'storefrontforeveryyoumaster', label: 'Storefront For Every You', showInSidebar: true },
    { path: '/fine-gold-master', pageKey: 'storefrontfinegoldmaster', label: 'Storefront Fine Gold', showInSidebar: true },
    { path: '/deserve-to-shine-master', pageKey: 'storefrontdeservetoshinemaster', label: 'Storefront Deserve To Shine', showInSidebar: true },
    { path: '/founder-message-master', pageKey: 'storefrontfoundermessagemaster', label: 'Storefront Founder Message', showInSidebar: true },
    { path: '/blog-section-master', pageKey: 'storefrontblogsectionmaster', label: 'Storefront Blog Section', showInSidebar: true },
    { path: '/shop-with-confidence-master', pageKey: 'storefrontshopwithconfidencemaster', label: 'Storefront Shop With Confidence', showInSidebar: true },
    { path: '/brand-story-master', pageKey: 'storefrontbrandstorymaster', label: 'Storefront Brand Story', showInSidebar: true },
    { path: '/reviews-master', pageKey: 'storefrontreviewsmaster', label: 'Storefront Reviews', showInSidebar: true },
    { path: '/cta-banner-master', pageKey: 'storefrontctabannermaster', label: 'Storefront CTA Banner', showInSidebar: true },
    { path: '/visit-stores-master', pageKey: 'storefrontvisitstoresmaster', label: 'Storefront Visit Stores', showInSidebar: true },
];
