const OccasionMasterJson = [
  {
    tabname: 'Occasion Master',
    pagename: 'Occasion Master',
    aliasname: 'occasionmaster',
    rightsidebarsize: 'md',
    fields: [
      {
        field: 'occasionname',
        text: 'Occasion Name',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'e.g. Office Wear',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 1,
        filtertype: 'text',
        filterplaceholder: 'Search occasion',
        label: 'Occasion Name',
      },
      {
        field: 'slug',
        text: 'URL Slug',
        type: 'text',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Auto from name if empty',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-160p',
        filter: 1,
        filtertype: 'text',
        filterplaceholder: 'Slug',
        label: 'Slug',
      },
      {
        field: 'sortorder',
        text: 'Sort Order',
        type: 'number',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Lower shows first',
        defaultvalue: 0,
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-100p',
        filter: 0,
      },
      {
        field: 'status',
        text: 'Status',
        type: 'checkbox',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Active',
        defaultvalue: 1,
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-100p',
        filter: 0,
      },
      {
        field: 'image',
        text: 'Carousel Image',
        type: 'image',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12',
        placeholder: 'Image URL',
        defaultvalue: '',
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-200p',
        filter: 0,
      },
      {
        field: 'description',
        text: 'Description',
        type: 'textarea',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12',
        placeholder: 'Optional subtitle / SEO text',
        defaultvalue: '',
        showingrid: false,
        sorting: false,
        tablesize: 'tbl-w-250p',
        filter: 0,
      },
    ],
  },
];

export default OccasionMasterJson;
