import Config from '../../../config/config';

const UserMasterJson = [
  {
    tabname: 'Basic Information',
    pagename: 'User Master',
    aliasname: 'usermaster',
    rightsidebarsize: 'md',
    fields: [
      {
        field: 'usercode',
        text: 'User Code',
        type: 'text',
        disabled: true,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter User Code',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 1,
        filtertype: 'text',
        filterplaceholder: 'Enter User Code',
        label: 'User Code',
      },
      {
        field: 'firstname',
        text: 'First Name',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter First Name',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'middlename',
        text: 'Middle Name',
        type: 'text',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Middle Name',
        defaultvalue: '',
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'lastname',
        text: 'Last Name',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Last Name',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'username',
        text: 'Username',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Username',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 1,
        filtertype: 'text',
        filterplaceholder: 'Enter Username',
        label: 'Username',
      },
      {
        field: 'email',
        text: 'Email',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Email',
        defaultvalue: '',
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'mobilenumber',
        text: 'Mobile Number',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Mobile Number',
        defaultvalue: '',
        maxlength: 15,
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'profileimage',
        text: 'Profile Image',
        type: 'image',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Profile Image URL',
        defaultvalue: '',
        showingrid: false,
        filter: 0,
      },
      {
        field: 'genderid',
        text: 'Gender',
        type: 'dropdown',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Select Gender',
        defaultvalue: '',
        masterdataarray: Config.genderOptions || [],
        masterdatafield: 'gender',
        formdatafield: 'gender',
        cleanable: true,
        searchable: true,
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'dateofbirth',
        text: 'Date of Birth',
        type: 'datepicker',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Select Date of Birth',
        defaultvalue: '',
        cleanable: true,
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
    ],
  },
  {
    tabname: 'Address',
    pagename: 'User Master',
    aliasname: 'usermaster',
    rightsidebarsize: 'md',
    fields: [
      {
        field: 'addressline1',
        text: 'Address Line 1',
        type: 'textarea',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12',
        placeholder: 'Enter Address Line 1',
        defaultvalue: '',
        showingrid: false,
        filter: 0,
      },
      {
        field: 'countryid',
        text: 'Country',
        type: 'dropdown',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        defaultvalue: '',
        masterdata: 'countrymaster',
        masterdatafield: 'countryname',
        formdatafield: 'country',
        cleanable: true,
        searchable: true,
        staticfilter: { status: 1 },
        onchangefill: ['stateid'],
        onchangedata: ['stateid'],
        projection: {
          countryname: 1,
          _id: 1,
        },

        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-250p',

        filter: 1,
        filtertype: 'text',
        label: 'Country',
      },
      {
        field: 'stateid',
        text: 'State',
        type: 'dropdown',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        defaultvalue: '',
        masterdata: 'statemaster',
        masterdatafield: 'statename',
        formdatafield: 'state',
        cleanable: true,
        searchable: true,
        // dependentfilter: { countryid: 'countryid' },
        statefilter: { status: 1 },
        dependentfilter: { countryid: 'countryid' },
        onchangefill: ['cityid'],
        onchangedata: ['cityid'],
        projection: {
          statename: 1,
          _id: 1,
        },

        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-250p',

        filter: 1,
        filtertype: 'text',
        label: 'state',
      },
      {
        field: 'cityid',
        text: 'City',
        type: 'dropdown',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Select City',
        defaultvalue: '',
        masterdata: 'citymaster',
        masterdatafield: 'cityname',
        formdatafield: 'city',
        statefilter: { status: 1 },
        dependentfilter: { stateid: 'stateid' },
        projection: {
          cityname: 1,
          _id: 1,
        },
        
        cleanable: true,
        searchable: true,
        showingrid: true,
        sorting: true,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
      {
        field: 'pincode',
        text: 'Pincode',
        type: 'text',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Pincode',
        defaultvalue: '',
        maxlength: 10,
        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-220p',
        filter: 0,
      },
    ],
  },
  {
    tabname: 'Account Details',
    pagename: 'User Master',
    aliasname: 'usermaster',
    rightsidebarsize: 'md',
    fields: [
      {
        field: 'password',
        text: 'Password',
        type: 'password',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Enter Password',
        defaultvalue: '',
        minlength: 8,
        showingrid: false,
        filter: 0,
        matchfield: 'confirmpassword',
        regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$',
        regexMessage: 'Password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, one number, and one special character',
      },
      {
        field: 'confirmpassword',
        text: 'Confirm Password',
        type: 'password',
        disabled: false,
        required: true,
        defaultvisibility: true,
        size: 'col-12 col-md-6',
        placeholder: 'Confirm Password',
        defaultvalue: '',
        minlength: 8,
        showingrid: false,
        filter: 0,
        matchfield: 'password',
        regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$',
        regexMessage: 'Password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, one number, and one special character',
      },
      {
        field: 'status',
        text: 'Status',
        type: 'checkbox',
        disabled: false,
        required: false,
        defaultvisibility: true,
        size: 'col-12',
        placeholder: 'Select Status',
        defaultvalue: 1,

        showingrid: true,
        sorting: false,
        tablesize: 'tbl-w-250p',

        filter: 0,
      },
    ],
  },
];

export default UserMasterJson;
