const grid = (showingrid, tablesize, sorting = false) => ({
    showingrid,
    tablesize: tablesize || 'tbl-w-160p',
    sorting,
    filter: 0,
});

const GeneralSettingMasterJson = [
    {
        tabname: 'General Settings',
        pagename: 'General Settings',
        aliasname: 'generalsetting',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'spin_popup_frequency_days',
                text: 'Spin Popup Frequency (in days)',
                type: 'number',
                required: false,
                sectionTitle: 'Spin to win',
                size: 'col-12 col-md-6',
                defaultvalue: '1',
                placeholder: '1 = daily, 3 = every 3 days',
                ...grid(true, 'tbl-w-160p', false),
            },
            {
                field: 'storeName',
                text: 'Store Name',
                type: 'text',
                required: true,
                sectionTitle: 'Basic store information',
                size: 'col-12 col-md-6',
                defaultvalue: 'ORINKET',
                ...grid(true, 'tbl-w-200p', true),
                filter: 1,
                filtertype: 'text',
                label: 'Store Name',
            },
            // {
            //     field: 'storeDescription',
            //     text: 'Store Description',
            //     type: 'textarea',
            //     required: false,
            //     sectionTitle: 'Basic store information',
            //     size: 'col-12',
            //     defaultvalue: 'Everyday demi-fine jewellery. Premium quality, accessible luxury.',
            //     ...grid(true, 'tbl-w-280p', false),
            // },
            {
                field: 'defaultCountryid',
                text: 'Default Currency',
                type: 'dropdown',
                required: true,
                sectionTitle: 'Basic store information',
                size: 'col-12 col-md-6',
                masterdata: 'countrymaster',
                masterdatafield: 'countryname',
                formdatafield: 'defaultCountry',
                showlableview: [
                    { field: 'countryname' },
                    { field: 'currencycode', prefix: ' (', suffix: ')' },
                ],
                staticfilter: { status: 1 },
                projection: { countryname: 1, currencycode: 1, _id: 1 },
                defaultvalue: '',
                searchable: true,
                cleanable: false,
                ...grid(false, 'tbl-w-250p', true),
            },
            {
                field: 'otherCurrencyPriceIncreasePercent',
                text: 'Increase Product Price (%)',
                type: 'text',
                required: false,
                sectionTitle: 'Basic store information',
                size: 'col-12 col-md-6',
                placeholder: 'e.g. 10 — applied when currency is not INR',
                defaultvalue: '0',
                visibleWhen: { field: 'defaultCurrency', notEquals: 'INR' },
                ...grid(true, 'tbl-w-270p', false),
            },
            {
                field: 'metaTitle',
                text: 'Meta Title',
                type: 'text',
                required: false,
                sectionTitle: 'SEO & meta (site-wide)',
                size: 'col-12',
                defaultvalue: 'ORINKET | Demi-Fine Jewellery | 18k Gold Plated - Shop Now',
                ...grid(true, 'tbl-w-260p', false),
            },
            {
                field: 'metaDescription',
                text: 'Meta Description',
                type: 'textarea',
                required: false,
                sectionTitle: 'SEO & meta (site-wide)',
                size: 'col-12',
                defaultvalue:
                    'Discover everyday demi-fine jewellery at Orinket. Premium 18k thick gold plated pieces that are trendy, lasting, and high on quality.',
                ...grid(true, 'tbl-w-280p', false),
            },
            {
                field: 'metaKeywords',
                text: 'Meta Keywords',
                type: 'textarea',
                required: false,
                sectionTitle: 'SEO & meta (site-wide)',
                size: 'col-12',
                defaultvalue: 'demi-fine jewellery, gold plated jewelry, 18k gold, necklaces, bracelets, earrings, rings',
                ...grid(true, 'tbl-w-260p', false),
            },
        ],
    },
    {
        tabname: 'Header',
        pagename: 'General Settings',
        aliasname: 'generalsetting',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'showTopBanner',
                text: 'Show Top Banner',
                type: 'checkbox',
                sectionTitle: 'Banner visibility',
                size: 'col-12 col-md-6',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-220p', false),
            },
            {
                field: 'showSecondaryBanner',
                text: 'Show Secondary Banner',
                type: 'checkbox',
                sectionTitle: 'Banner visibility',
                size: 'col-12 col-md-6',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-300p', false),
            },
            {
                field: 'topBannerDesktopText',
                text: 'Desktop Banner Text',
                type: 'textarea',
                sectionTitle: 'Banner copy',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-280p', false),
            },
            {
                field: 'topBannerMobileText',
                text: 'Mobile Banner Text',
                type: 'textarea',
                sectionTitle: 'Banner copy',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-260p', false),
            },
            {
                field: 'secondaryBannerText',
                text: 'Secondary Banner Text',
                type: 'textarea',
                sectionTitle: 'Banner copy',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-260p', false),
            },
        ],
    },
    {
        tabname: 'Footer',
        pagename: 'General Settings',
        aliasname: 'generalsetting',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'brandName',
                text: 'Brand Name',
                type: 'text',
                sectionTitle: 'Brand identity',
                size: 'col-12 col-md-6',
                defaultvalue: 'ORINKET',
                ...grid(true, 'tbl-w-180p', true),
            },
            {
                field: 'brandDescription',
                text: 'Brand Description',
                type: 'textarea',
                sectionTitle: 'Brand identity',
                size: 'col-12',
                defaultvalue: 'Everyday demi-fine jewellery. Premium quality, accessible luxury.',
                ...grid(true, 'tbl-w-280p', false),
            },
            {
                field: 'newsletterEnabled',
                text: 'Enable Newsletter',
                type: 'checkbox',
                sectionTitle: 'Newsletter',
                size: 'col-12 col-md-6',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'newsletterTitle',
                text: 'Newsletter Title',
                type: 'text',
                sectionTitle: 'Newsletter',
                size: 'col-12 col-md-6',
                defaultvalue: 'JOIN ORINKET FAMILY',
                ...grid(true, 'tbl-w-220p', false),
            },
            {
                field: 'newsletterDescription',
                text: 'Newsletter Description',
                type: 'textarea',
                sectionTitle: 'Newsletter',
                size: 'col-12',
                defaultvalue: 'Exclusive offers, new arrivals & styling tips',
                ...grid(true, 'tbl-w-260p', false),
            },
            {
                field: 'newsletterPlaceholder',
                text: 'Newsletter Placeholder',
                type: 'text',
                sectionTitle: 'Newsletter',
                size: 'col-12 col-md-6',
                defaultvalue: 'Your email',
                ...grid(true, 'tbl-w-280p', false),
            },
            {
                field: 'newsletterButtonText',
                text: 'Newsletter Button Text',
                type: 'text',
                sectionTitle: 'Newsletter',
                size: 'col-12 col-md-6',
                defaultvalue: 'SUBSCRIBE',
                ...grid(true, 'tbl-w-280p', false),
            },
            {
                field: 'categoryid',
                text: 'Category',
                type: 'dropdown',
                required: true,
                masterdata: 'category',
                masterdatafield: 'categoryname',
                formdatafield: 'category',
                staticfilter: { status: 1 },
                projection: { categoryname: 1, _id: 1 },
                size: 'col-12 col-md-6',
                defaultvalue: '',
                istablefield: true,
                rightsidebartablesize: 'tbl-w-220p',
            },
            {
                field: 'shopFooterLinks',
                text: 'Shop links',
                type: 'tbl-add-button',
                sectionTitle: 'Shop navigation',
                size: 'col-12',
                defaultvalue: [],
                tablefields: ['categoryid'],
                showingrid: false,
                filter: 0,
            },
            {
                field: 'urlCompanyAbout',
                text: 'About Us — URL',
                type: 'text',
                sectionTitle: 'Company links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/about',
                defaultvalue: '/about',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlCompanyStory',
                text: 'Our Story — URL',
                type: 'text',
                sectionTitle: 'Company links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/story',
                defaultvalue: '/story',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlCompanyStores',
                text: 'Stores — URL',
                type: 'text',
                sectionTitle: 'Company links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/stores',
                defaultvalue: '/stores',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlCompanyBlog',
                text: 'Blog — URL',
                type: 'text',
                sectionTitle: 'Company links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/blog',
                defaultvalue: '/blog',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlCompanyCareers',
                text: 'Careers — URL',
                type: 'text',
                sectionTitle: 'Company links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/careers',
                defaultvalue: '/careers',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlSupportContact',
                text: 'Contact Us — URL',
                type: 'text',
                sectionTitle: 'Support links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/contact',
                defaultvalue: '/contact',
                ...grid(true, 'tbl-w-220p', false),
            },
            {
                field: 'urlSupportFaq',
                text: 'FAQs — URL',
                type: 'text',
                sectionTitle: 'Support links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/faq',
                defaultvalue: '/faq',
                ...grid(true, 'tbl-w-160p', false),
            },
            {
                field: 'urlSupportShipping',
                text: 'Shipping Info — URL',
                type: 'text',
                sectionTitle: 'Support links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/shipping',
                defaultvalue: '/shipping',
                ...grid(true, 'tbl-w-230p', false),
            },
            {
                field: 'urlSupportReturns',
                text: 'Returns & Exchanges — URL',
                type: 'text',
                sectionTitle: 'Support links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/returns',
                defaultvalue: '/returns',
                ...grid(true, 'tbl-w-270p', false),
            },
            {
                field: 'urlSupportTrack',
                text: 'Track Order — URL',
                type: 'text',
                sectionTitle: 'Support links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/track',
                defaultvalue: '/track',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'urlLegalPrivacy',
                text: 'Privacy Policy — URL',
                type: 'text',
                sectionTitle: 'Legal links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/privacy',
                defaultvalue: '/privacy',
                ...grid(true, 'tbl-w-220p', false),
            },
            {
                field: 'urlLegalTerms',
                text: 'Terms of Service — URL',
                type: 'text',
                sectionTitle: 'Legal links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/terms',
                defaultvalue: '/terms',
                ...grid(true, 'tbl-w-260p', false),
            },
            {
                field: 'urlLegalRefund',
                text: 'Refund Policy — URL',
                type: 'text',
                sectionTitle: 'Legal links (fixed)',
                size: 'col-12 col-md-6',
                placeholder: '/refund',
                defaultvalue: '/refund',
                ...grid(true, 'tbl-w-250p', false),
            },
            {
                field: 'instagramUrl',
                text: 'Instagram URL',
                type: 'text',
                sectionTitle: 'Social media',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'facebookUrl',
                text: 'Facebook URL',
                type: 'text',
                sectionTitle: 'Social media',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'twitterUrl',
                text: 'X (Twitter) URL',
                type: 'text',
                sectionTitle: 'Social media',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'youtubeUrl',
                text: 'YouTube URL',
                type: 'text',
                sectionTitle: 'Social media',
                size: 'col-12',
                defaultvalue: '',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'pinterestUrl',
                text: 'Pinterest URL',
                type: 'text',
                sectionTitle: 'Social media',
                size: 'col-12',
                placeholder: 'https://pinterest.com/yourprofile',
                defaultvalue: '',
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'paymentVisa',
                text: 'Show Visa',
                type: 'checkbox',
                sectionTitle: 'Payment methods',
                size: 'col-12 col-md-3',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-150p', false),
            },
            {
                field: 'paymentMastercard',
                text: 'Show Mastercard',
                type: 'checkbox',
                sectionTitle: 'Payment methods',
                size: 'col-12 col-md-3',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-200p', false),
            },
            {
                field: 'paymentUpi',
                text: 'Show UPI',
                type: 'checkbox',
                sectionTitle: 'Payment methods',
                size: 'col-12 col-md-3',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-150p', false),
            },
            {
                field: 'paymentPaytm',
                text: 'Show PayTM',
                type: 'checkbox',
                sectionTitle: 'Payment methods',
                size: 'col-12 col-md-3',
                defaultvalue: 1,
                ...grid(true, 'tbl-w-150p', false),
            },
        ],
    },
    {
        tabname: 'SEO & Marketing',
        pagename: 'General Settings',
        aliasname: 'generalsetting',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'seoHomepageTitle',
                text: 'Homepage SEO Title',
                type: 'text',
                sectionTitle: 'Homepage SEO',
                size: 'col-12',
                defaultvalue: 'ORINKET | Demi-Fine Jewellery | 18k Gold Plated - Shop Now',
                ...grid(true, 'tbl-w-260p', false),
            },
            {
                field: 'seoHomepageMetaDescription',
                text: 'Homepage Meta Description',
                type: 'textarea',
                sectionTitle: 'Homepage SEO',
                size: 'col-12',
                defaultvalue:
                    'Discover everyday demi-fine jewellery at Orinket. Premium 18k thick gold plated pieces that are trendy, lasting, and high on quality.',
                ...grid(true, 'tbl-w-280p', false),
            },
        ],
    },
];

export default GeneralSettingMasterJson;
