import orinketHomePageSectionOptions from './orinketHomePageSectionOptions';
import Config from '../../../config/config';

const ProductMasterJson = [
    // ─── Tab 1: Basic Information ───────────────────────────────────────────────
    {
        tabname: 'Basic Information',
        pagename: 'Product Master',
        aliasname: 'productmaster',
        rightsidebarsize: 'lg',
        fields: [
            {
                field: 'productname',
                text: 'Product Name',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Product Name',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Product Name',
                label: 'Product Name',
            },
            {
                field: 'productseries',
                text: 'Product Series',
                type: 'text',
                disabled: true,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Loading next code… (final code fixed on Save)',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-200p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Product Series',
                label: 'Product Series',
            },
            {
                field: 'description',
                text: 'Description',
                type: 'textarea',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Enter Description',
                defaultvalue: '',
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
            },
            {
                field: 'availableQty',
                text: 'Available Qty',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'How many units can customers buy?',
                defaultvalue: 1,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-120p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Available Qty',
                label: 'Available Qty',
            },
            {
                field: 'status',
                text: 'Status',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Status',
                defaultvalue: 1,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-120p',
                filter: 0,
            },
        ],
    },

    // ─── Tab 2: Pricing ─────────────────────────────────────────────────────────
    {
        tabname: 'Pricing',
        fields: [
            {
                field: 'price',
                text: 'Price',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Selling Price',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Price',
                label: 'Price',
            },
            {
                field: 'originalPrice',
                text: 'Original Price',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Original / MRP',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Original Price',
                label: 'Original Price',
            },
            {
                field: 'buyOneGetOneFree',
                text: 'Buy 1 Get 1 Free',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '',
                defaultvalue: 0,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-140p',
                filter: 0,
            },
            {
                field: 'showIn925SilverPost',
                text: 'Show in 925 SILVER POST',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: '',
                defaultvalue: 0,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-180p',
                filter: 0,
            },
        ],
    },

    // ─── Tab 3: Category ────────────────────────────────────────────────────────
    {
        tabname: 'Category',
        fields: [
            {
                field: 'categoryid',
                text: 'Category',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Category',
                defaultvalue: '',
                masterdata: 'category',
                masterdatafield: 'categoryname',
                formdatafield: 'category',
                cleanable: true,
                searchable: true,
                staticfilter: { status: 1 },
                onchangefill: ['subcategoryid'],
                onchangedata: ['subcategoryid'],
                projection: {
                    categoryname: 1,
                    _id: 1,
                },
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'lookup',
                filterplaceholder: 'Enter Category',
                label: 'Category',
            },
            {
                field: 'subcategoryid',
                text: 'Sub Category',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Sub Category',
                defaultvalue: '',
                masterdata: 'subcategorymaster',
                masterdatafield: 'subcategoryname',
                formdatafield: 'subcategory',
                cleanable: true,
                searchable: true,
                staticfilter: { status: 1 },
                masterdatadependancy: true,
                dependentfilter: { categoryid: 'categoryid' },
                projection: {
                    subcategoryname: 1,
                    _id: 1,
                    categoryid: 1,
                },
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'lookup',
                filterplaceholder: 'Enter Sub Category',
                label: 'Sub Category',
            },
            {
                field: 'gender',
                text: 'Product For',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Select Product For',
                defaultvalue: '',
                masterdataarray: Config.productGenderOptions || [],
                masterdatafield: 'gender',
                formdatafield: 'gender',
                cleanable: false,
                searchable: true,
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-150p',
                filter: 1,
                filtertype: 'lookup',
                filterplaceholder: 'Enter Gender',
                label: 'Product For',
            },
            {
                field: 'occasionids',
                text: 'Occasions',
                type: 'multiselectpicker',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Select occasions',
                defaultvalue: [],
                masterdata: 'occasionmaster',
                masterdatafield: 'occasionname',
                staticfilter: { status: 1 },
                projection: {
                    occasionname: 1,
                    _id: 1,
                },
                showingrid: false,
                sorting: false,
                filter: 0,
            },
        ],
    },

    // ─── Tab 4: Media ───────────────────────────────────────────────────────────
    {
        tabname: 'Media',
        fields: [
            {
                field: 'images',
                text: 'Product Images',
                type: 'multipleimage',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Upload Product Images',
                defaultvalue: [],
                showingrid: false,
                filter: 0,
            },
        ],
    },

    // ─── Tab 5: Specifications ──────────────────────────────────────────────────
    {
        tabname: 'Specifications',
        fields: [
            {
                field: 'material',
                text: 'Material',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Material',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Material',
                label: 'Material',
            },
            {
                field: 'plating',
                text: 'Plating',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Plating',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Plating',
                label: 'Plating',
            },
            {
                field: 'dimensions',
                text: 'Dimensions',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Dimensions (e.g. 10x5x2 cm)',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Dimensions',
                label: 'Dimensions',
            },
            {
                field: 'weight',
                text: 'Weight',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12 col-md-6',
                placeholder: 'Enter Weight (e.g. 250g)',
                defaultvalue: '',
                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',
                filter: 1,
                filtertype: 'text',
                filterplaceholder: 'Enter Weight',
                label: 'Weight',
            },
        ],
    },

    // ─── Tab 6: Product Details ─────────────────────────────────────────────────
    {
        tabname: 'Product Details',
        fields: [
            {
                field: 'details',
                text: 'Products Detail(s)',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Enter Detail Label (e.g. Care Instructions)',
                defaultvalue: '',
                istablefield: true,
                rightsidebartablesize: 'tbl-w-200p',
            },
            {
                field: 'productdetails',
                text: 'Product Details Table',
                type: 'tbl-add-button',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: [],
                tablefields: ['details'],
            },
        ],
    },

    // ─── Tab 7: Marketing ───────────────────────────────────────────────────────
    {
        tabname: 'Marketing',
        fields: [
            {
                field: 'storefrontHomeSectionKeys',
                text: 'Product Listed On',
                type: 'multiselectpicker',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Select Product Listed On',
                defaultvalue: [],
                masterdataarray: orinketHomePageSectionOptions,
                showingrid: false,
                sorting: false,
                filter: 0,
            },
        ],
    },
];

export default ProductMasterJson;