const ProductMasterJson = [
    {
        tabname: 'Product Master',
        pagename: 'Product Master',
        aliasname: 'productmaster',
        rightsidebarsize: 'sm',
        fields: [
            {
                field: 'productname',
                text: 'Product Name',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Product Name',
            },
            {
                field: 'price',
                text: 'Price',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Price',
            },
            {
                field: 'originalPrice',
                text: 'Original Price',
                type: 'number',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Original Price',
            },
            {
                field: 'categoryid',
                text: 'Category',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                masterdata: 'category',
                masterdatafield: 'categoryname',
                formdatafield: 'category',
                staticfilter: { status: 1 },
                onchangefill: ['subcategoryid'],
                onchangedata: ['subcategoryid'],
                projection: {
                    categoryname: 1,
                    _id: 1,
                },

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Category',
            },
            {
                field: 'subcategoryid',
                text: 'Sub Category',
                type: 'dropdown',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                masterdata: 'subcategorymaster',
                masterdatafield: 'subcategoryname',
                formdatafield: 'subcategory',
                staticfilter: { status: 1 },
                dependentfilter: { categoryid: 'categoryid' },
                projection: {
                    subcategoryname: 1,
                    _id: 1,
                },

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Sub Category',
            },
            // {
            //     field: 'image',
            //     text: 'Image',
            //     type: 'image',
            //     disabled: false,
            //     required: true,
            //     defaultvisibility: true,
            //     size: 'col-12 col-md-6',
            //     placeholder: 'Product Image URL',
            //     defaultvalue: '',
            //     showingrid: false,
            //     filter: 0,
            // },
            {
                field: 'images',
                text: 'Product Images',
                type: 'multipleimage',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Product Images URL',
                defaultvalue: [],
                showingrid: false,
                filter: 0,
            },
            {
                field: 'description',
                text: 'Description',
                type: 'textarea',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Enter Description',
                defaultvalue: '',

                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-250p',

                filter: 0,
            },
            {
                field: 'instock',
                text: 'In Stock',
                type: 'radio',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                options: [
                    { label: 'In Stock', value: 1 },
                    { label: 'Out of Stock', value: 0 },
                ],
                defaultvalue: 1,
                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-250p',
                filter: 0,
            },
            {
                field: 'material',
                text: 'Material',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Material',
            },
            {
                field: 'plating',
                text: 'Plating',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Plating',
            },
            {
                field: 'dimensions',
                text: 'Dimensions',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Dimensions',
            },
            {
                field: 'weight',
                text: 'Weight',
                type: 'text',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',

                showingrid: true,
                sorting: true,
                tablesize: 'tbl-w-250p',

                filter: 1,
                filtertype: 'text',
                label: 'Weight',
            },
            {
                field: 'details',
                text: 'Product Details',
                type: 'text',
                disabled: false,
                required: true,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: '',
                istablefield: true,

                rightsidebartablesize: 'tbl-w-200p',
            },
            {
                field: 'productdetails',
                text: 'Product Details Table',
                type: 'tbl-add-button',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                defaultvalue: [],
                tablefields: ['details'],
            },
            {
                field: 'status',
                text: 'Status',
                type: 'checkbox',
                disabled: false,
                required: false,
                defaultvisibility: true,
                size: 'col-12',
                placeholder: 'Select Status',
                defaultvalue: 1,

                showingrid: true,
                sorting: false,
                tablesize: 'tbl-w-250p',

                filter: 0,
            },
        ],
    },
];

export default ProductMasterJson;
